org: anthonysorg
service: foodiary-api

provider:
  name: aws
  region: us-east-1
  runtime: nodejs24.x
  memorySize: 128
  stage: ${opt:stage, 'dev'}
  httpApi:
    authorizers:
      cognitoAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: !Sub https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}
        audience:
          - !Ref UserPoolClient

package:
  individually: true

custom:
  cognito:
    PoolName: ${self:service}-${self:provider.stage}-UserPool

build:
  esbuild:
    configFile: ./esbuild.config.mjs

functions:
  hello:
    handler: src/main/functions/hello.handler
    events:
      - httpApi:
          path: /hello/{id}
          method: POST
          authorizer:
            name: cognitoAuthorizer

resources:
  - ${file(./sls/cognito.yml)}
